In [22]:
%matplotlib inline
from ipyparallel import Client
import statsmodels.api as sm
import numpy as np

In [23]:
data_loader = sm.datasets.sunspots.load_pandas()
vals = data_loader.data['SUNACTIVITY'].values
glob_mean = vals.mean()
glob_mean

49.752103559870541

In [31]:
c = Client(profile='mpi')

In [32]:
view = c[:]

In [33]:
view.activate()

In [34]:
view.run('mpi_ipython.py')

<AsyncResult: execute>

In [35]:
view.scatter('a',np.arange(len(vals),dtype='int'))

<AsyncResult: scatter>

In [36]:
view['a']

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38]),
 array([39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77]),
 array([ 78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116]),
 array([117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155]),
 array([156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
        182, 183, 184, 185, 186, 187, 188, 189, 

In [37]:
%px means = jackknife(a)

<AsyncResult: execute>

In [21]:
view['means']

CompositeError: one or more exceptions from call to method: _pull
[0:apply]: NameError: name 'means' is not defined
[1:apply]: NameError: name 'means' is not defined
[2:apply]: NameError: name 'means' is not defined
[3:apply]: NameError: name 'means' is not defined
.... 4 more exceptions ...

In [ ]:
all_means = []

for v in view['means']:
    all_means.extend(v)
    
mean(all_means)

In [ ]:
std(all_means)

In [ ]:
hist(all_means, bins=sqrt(len(all_means)))

In [ ]:
[(k, c.metadata[k]['started'], c.metadata[k]['pyout'], c.metadata[k]['pyerr']) for k in c.metadata.keys()]